export enum FileType {
    PROFILE_IMAGE         = "PROFILE_IMAGE",
    ID_DOCUMENT           = "ID_DOCUMENT",          
    SIGNATURE             = "SIGNATURE",           
    MEDICAL_LICENSE       = "MEDICAL_LICENSE",      
    LIABILITY_INSURANCE   = "LIABILITY_INSURANCE", 
    DEGREE_CERTIFICATE    = "DEGREE_CERTIFICATE",  
    SPECIALTY_CERTIFICATE = "SPECIALTY_CERTIFICATE", 
    PRESCRIPTION          = "PRESCRIPTION",         
    MEDICAL_REPORT        = "MEDICAL_REPORT"
}