import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { StateContextProvider } from "@/utils/context/StateContext";
import WhatsAppWidget from "@/components/WhatsAppWidget";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Website Anita",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <StateContextProvider> 
          {children}
        </StateContextProvider>
        <WhatsAppWidget />
      </body>
    </html>
  );
}
